### PR TITLE
Sprint5 bigfish

### PR DESCRIPTION
**Pull request by IAmAllOfYou**
big fish AI, seeks player where ever he is. seeks flare over the player. if player is in a safe zone then he goes to a "waypoint" if the player is in a safe zone

### CODE REVIEW

**Comment by stellarxo** [comment]
@IAmAllOfYou can you resolve the conflicts and recommit?

**Comment by IAmAllOfYou** [comment]
this branch is broken so look at sprint8_bigfish instead

**Comment by alisterdev** [comment]
@IAmAllOfYou the other branch equally has merge conflicts

**Comment by alisterdev** [comment]
Since stuff is now on sprint8_bigfish, closing this one

**Pull request closed without merging**
