### PR TITLE
Implementing Priority Dictionary - Revised

### PR DESCRIPTION
**Pull request by stellarxo**
Uses three priority dictionaries to keep track of which action to execute
each dictionary uses a unique fish ID for each entry

https://github.com/FeedJonathanFoundation/ubisoft-game-lab/pull/35

### CODE REVIEW

**Comment by johnny-la** [comment]
Great work, this looks like a scalable solution to an AI controller

### TODOs
* Remove the player seek action in `OnTriggerExit()`. Currently the fish will always pursue the player  , even if he becomes out of sight.

**Comment by stellarxo** [comment]
@johnny-la I think that the ontrigger exit comment should be implemented in the future, and for specific fish only (and only if the player's light is on?) 
I will make a trello card for this.

**Comment by stellarxo** [comment]
@johnny-la 
"We could have a set of "always running" steering behaviours such as cohesion, alignment and obstacle avoidance stored in a List<NPCActionable>."

Made a list inside priority dictionary where these are stored.

**Comment by johnny-la** [comment]
Looks good, branch merged

**Pull request merged**
