### PR TITLE
Sound Refactor

### PR DESCRIPTION
**Pull request by stellarxo**

### CODE REVIEW

**Comment by stellarxo** [comment]
Wondering if the sound functions should be more generic - like 
PlaySound("Eat", this.gameObject); in the client classes
and have a switch statement or something in the sound manager class

**Comment by stellarxo** [comment]
do not merge - it breaks everything

**Comment by stellarxo** [comment]
ambient sounds not working when next scene is loaded
need to restart current stage when player restarts

**Comment by alisterdev** [comment]
😢

**Comment by stellarxo** [comment]
🤷🏻‍♀️

**Comment by Simon-Thompson** [comment]
🥇 💯 👍

**Pull request closed without merging**
