### PR TITLE
Restructured player class for OOP ways

### PR DESCRIPTION
**Pull request by alisterdev**
@stellarxo and @johnny-la, please review this attempt to OOP the player class and leave your feedback

### CODE REVIEW

**Comment by alisterdev** [comment]
Additionally, I plan to create an abstract CharacterAction class from which Movement and stuff will extend...

**Comment by stellarxo** [comment]
Looks good to me - and it compiles!

**Comment by alisterdev** [comment]
@stellarxo  Of course it does, I only push the code that compiles :100:

**Comment by johnny-la** [comment]
OOP refactoring incorporated into sprint2_mass_system

**Comment by alisterdev** [comment]
yay

**Pull request closed without merging**
